//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Леарн.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientService()
        {
            this.Session_DocumentByService = new HashSet<DocumentByService>();
            this.Session_ProductSale = new HashSet<ProductSale>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Comment { get; set; }

        public string Title
        {
            get
            {
                return Session_Service.Title;
            }
        }
        public string Fio
        {
            get
            {
                return"Клиент: "+Session_Client.Fio;
            }
        }
        public string Pochta
        {
            get
            {
                return "Почта: "+ Session_Client.Email;
            }
        }
        public string Phone
        {
            get
            {
                return "Телефон: " + Session_Client.Phone;
            }
        }
        public string TimeToStart
        {
            get
            {
                return "Время до начала: " + (StartTime- DateTime.Now).ToString("d' д. 'h' ч. 'm' мин. 's' сек.'");
            }
        }
        public virtual Client Session_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentByService> Session_DocumentByService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> Session_ProductSale { get; set; }
        public virtual Service Session_Service { get; set; }
    }
}
