//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Леарн.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Session_ClientService = new HashSet<ClientService>();
            this.Session_ServicePhoto = new HashSet<ServicePhoto>();
        }

        public int ID { get; set; }
        public string Title { get; set; }
        public int Cost { get; set; }
        public int DurationInSeconds { get; set; }
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        public string MainImagePath { get; set; }
        public string CostDuration
        {
            get
            {   if(Discount==0|| Discount == null)
                {
                    return Cost.ToString() + " рублей " + "за " + DurationInSeconds / 60 + " минут.";
                }
                else
                {
                    return ((double)Cost * (1.00 - Discount)).ToString() + " рублей " + "за " + DurationInSeconds / 60 + " минут.";
                }
                
            }
        }

        public string DiscountInPresent
        {
            get
            {
                if (Discount * 100 > 0)
                {
                    return "* скидка " + Discount * 100 + " %";
                }
                return " ";
            }
        }
      

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> Session_ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> Session_ServicePhoto { get; set; }
    }
}
